# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: trailing-whitespace             #This hook trims all whitespace from the end of each line
    -   id: end-of-file-fixer               #This hooks ensures that all files end in a newline and only a newline.
    -   id: mixed-line-ending
        args:   [ '--fix=lf' ]
    -   id: pretty-format-json
        args:   [ '--indent="   "' ]
    -   id: trailing-whitespace
        args:   [ '--markdown-linebreak-ext=md' ]
    -   id: check-added-large-files         # this hook will prevent  extremely large files from being committed.
        args:   [ '--maxkb=20000' ]

-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: [--line-length=88]
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args:
            - --max-line-length=88

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.3
    hooks:
    -   id: nbqa-black
    -   id: nbqa-isort
    -   id: nbqa-flake8
    -   id: nbqa-check-ast
# Suppressed for now
#-   repo: https://github.com/markdownlint/markdownlint
#    rev: 0.13.0
#    hooks:
#    -   id: markdownlint
#        name: Markdownlint
#        description: Run markdownlint on your Markdown files
#        entry: mdl
#        language: ruby
#        files: \.(md|mdown|markdown)$
#-   repo: https://github.com/econchick/interrogate
#    rev: 1.5.0
#    hooks:
#    -   id: interrogate
#        args: [-vv, -i, --fail-under=80]
#-   repo: https://github.com/PyCQA/autoflake
#    rev: "1.4"
#    hooks:
#    -   id: autoflake
#        args: [--in-place, --remove-unused-variables]
