[project]
name = "sjmelck-pages"
version = "0.1.0"
description = "A blog created by Douw Marx and Ryan Balshaw, currently maintained by Ryan Balshaw."
readme = "README.md"
authors = [
    { name = "Ryan Balshaw", email = "ryanbalshaw81@gmail.com" }
]
requires-python = ">=3.10.13,<3.13"
dependencies = [
    "matplotlib>=3.10.9",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "scipy>=1.15.3",
]

[project.scripts]
sjmelck-pages = "sjmelck_pages:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipympl>=0.10.0",
    "jupyterlab>=4.6.3",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
