"""Turn a marimo notebook into a publishable Hugo post.

``marimo export md`` gets most of the way, but it drops cell outputs, emits
its own front matter, and leaves inline maths in a form Goldmark mangles.
This module fixes those up and reports what still needs a human.
"""

from __future__ import annotations

import importlib.util
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from sjmelck_pages.marimo_cli import mdfix
from sjmelck_pages.marimo_cli.repo import (
    RepoError,
    image_dir,
    relative_to_root,
)

GENERATED_BY = (
    "# Generated by `sjmelck-pages convert` from {source} "
    "- edit the notebook, not this file."
)
PLACEHOLDERS = ("dummy-name", "dummy-description", "tag1", "tag2", "tag3", "category1")
IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg"}

ERROR, WARNING, INFO = "error", "warning", "info"


@dataclass(frozen=True)
class Note:
    """One line of the report printed after a conversion."""

    level: str
    message: str


@dataclass
class ConversionResult:
    text: str
    slug: str
    notes: list[Note] = field(default_factory=list)
    referenced_images: list[str] = field(default_factory=list)
    converted_math: int = 0
    hidden_cells: int = 0

    @property
    def errors(self) -> list[Note]:
        return [n for n in self.notes if n.level == ERROR]

    @property
    def warnings(self) -> list[Note]:
        return [n for n in self.notes if n.level == WARNING]


def _require_marimo() -> None:
    """marimo is a dev dependency, so it is missing only if nobody synced."""
    if importlib.util.find_spec("marimo") is None:
        raise RepoError(
            "marimo is not installed in this environment. Run `uv sync` to "
            "install the dev dependency group."
        )


def export_notebook(notebook: Path) -> str:
    """Run ``marimo export md`` and return the markdown."""
    _require_marimo()
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "export.md"
        completed = subprocess.run(
            [
                sys.executable,
                "-m",
                "marimo",
                "export",
                "md",
                str(notebook),
                "-o",
                str(out),
                "-f",
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if not out.exists():
            detail = (completed.stderr or completed.stdout or "").strip()
            raise RepoError(f"marimo export failed:\n{detail}")
        return out.read_text(encoding="utf-8")


def run_notebook(notebook: Path) -> None:
    """Execute the notebook as a script so its figures are regenerated.

    A marimo notebook is a valid Python script, so the interpreter running
    this command runs the notebook too - the same environment that holds
    marimo also holds matplotlib and numpy.
    """
    _require_marimo()
    completed = subprocess.run(
        [sys.executable, str(notebook)],
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout or "").strip()
        raise RepoError(f"Running the notebook failed:\n{detail}")


def _block_bounds(lines: list[str], start: int) -> int | None:
    """Index of the ``---`` closing a front-matter block opened at ``start``."""
    for index in range(start + 1, len(lines)):
        if lines[index].strip() == "---":
            return index
    return None


def split_front_matter(text: str) -> tuple[str | None, str]:
    """Separate the Sjmelck front matter from the body.

    marimo emits its own block first; that one is always discarded. If the
    next non-blank line opens another block, it is the front matter the
    author wrote in the notebook's first cell.
    """
    lines = text.splitlines()
    cursor = 0
    while cursor < len(lines) and not lines[cursor].strip():
        cursor += 1

    if cursor >= len(lines) or lines[cursor].strip() != "---":
        return None, text

    marimo_end = _block_bounds(lines, cursor)
    if marimo_end is None:
        return None, text

    cursor = marimo_end + 1
    while cursor < len(lines) and not lines[cursor].strip():
        cursor += 1

    if cursor >= len(lines) or lines[cursor].strip() != "---":
        return None, "\n".join(lines[marimo_end + 1 :])

    sjmelck_end = _block_bounds(lines, cursor)
    if sjmelck_end is None:
        return None, "\n".join(lines[marimo_end + 1 :])

    front = "\n".join(lines[cursor : sjmelck_end + 1])
    body = "\n".join(lines[sjmelck_end + 1 :])
    return front, body


def _field(front: str, name: str) -> str | None:
    match = re.search(rf"^{re.escape(name)}:\s*(.*?)\s*$", front, flags=re.MULTILINE)
    return match.group(1) if match else None


def _unquote(value: str) -> str:
    return value.strip().strip('"').strip("'")


def check_post(
    front: str,
    body: str,
    *,
    slug: str,
    folder: Path,
    referenced: list[str],
    converted_math: int,
    now: datetime,
) -> list[Note]:
    """Everything worth telling the author before they open a pull request."""
    notes: list[Note] = []

    published = _field(front, "publishdate")
    if not published:
        notes.append(Note(ERROR, "publishdate is missing from the front matter."))
    else:
        try:
            moment = datetime.fromisoformat(_unquote(published))
        except ValueError:
            notes.append(Note(ERROR, f"publishdate {published!r} is not ISO 8601."))
        else:
            if moment.tzinfo is None:
                notes.append(Note(WARNING, "publishdate has no timezone offset."))
            elif moment > now:
                notes.append(
                    Note(
                        ERROR,
                        f"publishdate {published} is in the future, so Hugo will "
                        "silently leave this post out of the build.",
                    )
                )

    for name in referenced:
        if not (folder / name).exists():
            notes.append(
                Note(ERROR, f"Referenced image {name!r} is not in {folder.name}/.")
            )

    overview = _field(front, "OverviewFig")
    if not overview:
        notes.append(
            Note(WARNING, "OverviewFig is not set, so the post card has no thumbnail.")
        )
    elif not (folder / _unquote(overview)).exists():
        notes.append(Note(WARNING, f"OverviewFig {overview} does not exist."))

    if converted_math and "math: true" not in front:
        notes.append(
            Note(ERROR, "Inline maths was converted but `math: true` is not set.")
        )

    if mdfix.has_mermaid_fence(body) and "hasMermaid: true" not in front:
        notes.append(
            Note(ERROR, "A mermaid block is present but `hasMermaid: true` is not set.")
        )

    for placeholder in PLACEHOLDERS:
        if placeholder in front:
            notes.append(
                Note(
                    WARNING,
                    f"Front matter still contains the placeholder {placeholder!r}.",
                )
            )

    description = _field(front, "description")
    if description:
        length = len(_unquote(description))
        if not 120 <= length <= 160:
            notes.append(
                Note(
                    WARNING,
                    f"description is {length} characters; aim for 120 to 160.",
                )
            )

    fences = mdfix.iter_code_fences(body)
    lines = body.splitlines()
    fence_text = "\n".join(
        "\n".join(lines[start : end + 1]) for start, end, _ in fences
    )
    if "mo.ui." in fence_text:
        notes.append(
            Note(
                WARNING,
                "A cell uses mo.ui - interactive widgets do not survive export.",
            )
        )
    if "mo.md(f" in fence_text:
        notes.append(
            Note(WARNING, 'mo.md(f"...") cannot be exported; use a plain string.')
        )

    fenced_lines: set[int] = set()
    for start, end, _info in fences:
        fenced_lines.update(range(start, end + 1))
    for index, line in enumerate(lines):
        if index not in fenced_lines and re.match(r"^#\s+\S", line):
            notes.append(
                Note(WARNING, f"Heading on line {index + 1} starts at `#`; use `##`.")
            )
            break

    if folder.is_dir():
        present = {
            item.name
            for item in folder.iterdir()
            if item.is_file() and item.suffix.lower() in IMAGE_SUFFIXES
        }
        unused = sorted(present - set(referenced))
        if unused:
            notes.append(
                Note(
                    INFO, f"Unreferenced images in {folder.name}/: {', '.join(unused)}"
                )
            )

    if "draft: true" in front:
        notes.append(Note(INFO, "draft: true - set it to false before merging."))

    return notes


def convert(
    exported: str,
    *,
    slug: str,
    folder: Path,
    now: datetime,
    source: str,
    keep_attrs: bool = False,
) -> ConversionResult:
    """Run the whole text pipeline over marimo's exported markdown."""
    front, body = split_front_matter(exported)
    notes: list[Note] = []

    if front is None:
        # Generating a placeholder block would put it in the generated post,
        # where any edit is lost on the next conversion.
        raise RepoError(
            "No front matter found in the notebook. Add it to the notebook's "
            "first cell; `sjmelck-pages new` scaffolds one."
        )

    body, hidden = mdfix.strip_hidden_cells(body)
    if not keep_attrs:
        body = mdfix.strip_fence_attributes(body)

    math = mdfix.convert_inline_math(body)
    body = math.text

    body, referenced = mdfix.normalize_image_links(body, slug)

    if math.unmatched_dollars:
        notes.append(
            Note(
                INFO,
                "Unmatched `$` left on lines "
                + ", ".join(str(n) for n in math.unmatched_dollars[:10]),
            )
        )

    notes.extend(
        check_post(
            front,
            body,
            slug=slug,
            folder=folder,
            referenced=referenced,
            converted_math=math.converted,
            now=now,
        )
    )

    front_lines = front.splitlines()
    stamped = "\n".join(
        [front_lines[0], GENERATED_BY.format(source=source), *front_lines[1:]]
    )
    text = mdfix.normalise_whitespace(stamped + "\n\n" + body.strip() + "\n")

    return ConversionResult(
        text=text,
        slug=slug,
        notes=notes,
        referenced_images=referenced,
        converted_math=math.converted,
        hidden_cells=hidden,
    )


def convert_notebook(
    root: Path,
    notebook: Path,
    *,
    slug: str | None = None,
    now: datetime,
    from_markdown: Path | None = None,
    execute: bool = False,
    keep_attrs: bool = False,
) -> ConversionResult:
    """Export a notebook and convert it, without writing anything."""
    resolved = slug or notebook.stem
    folder = image_dir(root, resolved)

    if from_markdown is not None:
        exported = from_markdown.read_text(encoding="utf-8")
    else:
        if not notebook.is_file():
            raise RepoError(f"No notebook at {notebook}")
        if execute:
            run_notebook(notebook)
        exported = export_notebook(notebook)

    return convert(
        exported,
        slug=resolved,
        folder=folder,
        now=now,
        source=relative_to_root(root, notebook),
        keep_attrs=keep_attrs,
    )
